### ISSUE TITLE
Wide shadow

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu-flutter-community/handy_window#26]
I've noticed that my screenshots have had super wide shadows lately. Is it coming from here?

![image](https://user-images.githubusercontent.com/140617/216810764-b358a3b1-be07-4087-8a94-798eaa679b48.png)

**Comment by Feichtmeier** [comment]
> I've noticed that my screenshots have had super wide shadows lately. Is it coming from here?
> 
> ![image](https://user-images.githubusercontent.com/140617/216810764-b358a3b1-be07-4087-8a94-798eaa679b48.png)
> 

I've noticed the same! Good question
Does it also happen if you screenshot discord? Since it's made with react native

**Comment by jpnurmi** [comment]
yaru_widgets example with handy_window removed:

![image](https://user-images.githubusercontent.com/140617/216811075-3c829e02-a4de-4857-a83a-44485b9ceb16.png)

**Comment by jpnurmi** [comment]
| Before #22 | After #22 |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/216811659-8dd3655d-5aef-456e-b961-9678df3c0e80.png) | ![image](https://user-images.githubusercontent.com/140617/216811663-4f3807cf-67f0-4268-ac55-414208e1b27e.png) |

/cc @Jupi007

**Comment by Jupi007** [comment]
It is "normal" because I copied-pasted the shadow from Libadwaita.
But, I just compared nautilus with the handy_window example, and it looks like box-shadow properties are not interpreted in the same way in Gtk3 as in Gtk4... The Libadwaita shadow is bigger than the Gtk3 one, but handy_window one is even larger.

I'll try to adjust that :)

**Comment by jpnurmi** [comment]
@Jupi007 Did you have time to take a look? I noticed that the wide shadow is included in the minimum window size, too. Unfortunately, GDK includes shadows in the minimum window size. :(

**Comment by Jupi007** [comment]
Oh, okay. In fact I had just started to work a little bit on :)
But I'll revert it to the original one, I think it is the best thing to do.
I didn't know that the shadow was take in account like that.

**Comment by jpnurmi** [comment]
Me neither. :) I only realized it because the wide shadow made it possible to resize the software store window very small.

**Comment by jpnurmi** [comment]
Is it possible to revert the shadow only but keep the colors?

**Comment by Jupi007** [comment]
What do you mean? Which colors? 🤔

**Comment by jpnurmi** [comment]
Didn't we change the colors to match libadwaita? Or did I confuse things with the YaruTitleBar colors? :D

**Comment by Jupi007** [comment]
Oh, you mean the headerbar (I was searching something colorful 😅).
It won't be affected, nor the bright dark theme border :)
