### ISSUE TITLE
White line on top when maximised

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/handy_window#31]
The line isn't there when the window is snapped to the left or right.

Also from what @Jupi007 said, this issue only arises when the themed used is adwaita.

[Screencast from 2023-02-11 20-33-09.webm](https://user-images.githubusercontent.com/73116038/218279996-15ef55bc-a8f3-4fdf-a3f9-342a726567fe.webm)

**Comment by Jupi007** [comment]
Thanks @whiskeyPeak I will look into this.
