### ISSUE TITLE
`fatal error: 'fribidi.h' file not found`

### ISSUE THREAD

**Issue by Henry-Hiles** [ubuntu-flutter-community/handy_window#51]
I'm getting this error when trying to build my flutter app: `/home/quadradical/Documents/Code/quados/settings/linux/flutter/ephemeral/.plugin_symlinks/handy_window/linux/libhandy/src/src/hdy-bidi.c:29:10: fatal error: 'fribidi.h' file not found`

I tried using a nix shell of fribidi but it didn't work. Any help would be appreciated, thanks!

**Comment by Henry-Hiles** [comment]
I think this would also be fixed if #34 was implemented.

**Comment by Feichtmeier** [comment]
> I'm getting this error when trying to build my flutter app: `/home/quadradical/Documents/Code/quados/settings/linux/flutter/ephemeral/.plugin_symlinks/handy_window/linux/libhandy/src/src/hdy-bidi.c:29:10: fatal error: 'fribidi.h' file not found`
> 
> I tried using a nix shell of fribidi but it didn't work. Any help would be appreciated, thanks!

could you link to your app if it is open source? then I can check what eventrually went wrong

**Comment by Henry-Hiles** [comment]
> > I'm getting this error when trying to build my flutter app: `/home/quadradical/Documents/Code/quados/settings/linux/flutter/ephemeral/.plugin_symlinks/handy_window/linux/libhandy/src/src/hdy-bidi.c:29:10: fatal error: 'fribidi.h' file not found`
> > I tried using a nix shell of fribidi but it didn't work. Any help would be appreciated, thanks!
> 
> could you link to your app if it is open source? then I can check what eventrually went wrong

I believe it's actually related to nix. I removed handy for now, I'll send the app repo when I re-add it later.

**Comment by Henry-Hiles** [comment]
Don't worry, i didn't install it properly with nix, thx.
